<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3de92bd3c2e6340f54062fa15084c8fb
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'ReCaptcha\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ReCaptcha\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/recaptcha/src/ReCaptcha',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3de92bd3c2e6340f54062fa15084c8fb::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3de92bd3c2e6340f54062fa15084c8fb::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
